# Generated by Django 5.0.1 on 2024-01-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='wdate',
            new_name='cdate',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
