# Generated by Django 5.0.1 on 2024-01-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_wdate_blogmodel_cdate_blogmodel_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='cdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='udate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
