# Generated by Django 5.0.1 on 2024-01-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_blogmodel_cdate_alter_blogmodel_udate'),
    ]

    operations = [
        migrations.CreateModel(
            name='a1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
