# Generated by Django 5.0.1 on 2024-01-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_a1model_a1image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='cdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='udate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
